// REQ-EXP-001 to REQ-EXP-014: JSON and PDF export of assessment results
// S07-01: JSON export with versioned schema and credential masking
// S07-02: PDF export with summary, per-class breakdowns, and failed test details

import PDFDocument from 'pdfkit';
import { CredentialMasker } from '@/engine/credential-masker';
import type {
  AssessmentResults,
  AuthConfig,
  ConformanceClassResult,
  HttpExchange,
} from '@/lib/types';

/** Disclaimer included in all exports. REQ-EXP-007. */
const DISCLAIMER =
  'This report is generated by an automated compliance assessment tool. ' +
  'Results should be verified by a qualified professional before making ' +
  'conformance claims. This tool is not an official OGC certification authority.';

/** Result of a JSON export operation. */
export interface ExportJsonResult {
  /** Schema version for forward compatibility. REQ-EXP-005. */
  schemaVersion: string;
  /** ISO 8601 timestamp of when the export was generated. */
  exportedAt: string;
  /** Disclaimer text. REQ-EXP-007. */
  disclaimer: string;
  /** Serialized assessment results with masked credentials. */
  data: Record<string, unknown>;
}

/**
 * Convert a Map<string, HttpExchange> to a plain object for JSON serialization.
 */
function exchangesToObject(
  exchanges: Map<string, HttpExchange>,
): Record<string, HttpExchange> {
  const obj: Record<string, HttpExchange> = {};
  for (const [id, exchange] of exchanges) {
    obj[id] = exchange;
  }
  return obj;
}

/**
 * Generate a filename for the export following the convention:
 * csapi-compliance-{hostname}-{date}.{ext}
 * REQ-EXP-008.
 */
export function generateFilename(
  endpointUrl: string,
  ext: 'json' | 'pdf',
): string {
  let hostname = 'unknown';
  try {
    hostname = new URL(endpointUrl).hostname.replace(/[^a-zA-Z0-9.-]/g, '_');
  } catch {
    // Use default
  }
  const date = new Date().toISOString().slice(0, 10); // YYYY-MM-DD
  return `csapi-compliance-${hostname}-${date}.${ext}`;
}

/**
 * Export engine that produces JSON and PDF reports from assessment results.
 * Applies credential masking to all exported data.
 */
export class ExportEngine {
  /**
   * Export assessment results as JSON with a versioned schema.
   * REQ-EXP-001 to REQ-EXP-008.
   *
   * - Schema version "1" for forward compatibility (REQ-EXP-005)
   * - Masks credentials via CredentialMasker (REQ-EXP-003)
   * - Includes disclaimer text (REQ-EXP-007)
   * - Converts Map<string, HttpExchange> to plain object for JSON serialization
   */
  exportJson(results: AssessmentResults, auth: AuthConfig): ExportJsonResult {
    // Mask credentials in all HTTP exchanges
    const maskedExchanges = CredentialMasker.maskAll(results.exchanges, auth);

    // Build the serializable data object
    const data: Record<string, unknown> = {
      id: results.id,
      endpointUrl: results.endpointUrl,
      startedAt: results.startedAt,
      completedAt: results.completedAt,
      status: results.status,
      classes: results.classes,
      exchanges: exchangesToObject(maskedExchanges),
      summary: results.summary,
    };

    return {
      schemaVersion: '1',
      exportedAt: new Date().toISOString(),
      disclaimer: DISCLAIMER,
      data,
    };
  }

  /**
   * Export assessment results as a PDF document.
   * REQ-EXP-009 to REQ-EXP-014.
   *
   * Layout:
   * - Page 1: Title, endpoint URL, date, overall compliance %, summary stats, disclaimer
   * - Page 2+: Per-conformance-class sections with status, test counts
   * - Failed tests section: requirement URI and failure message
   *
   * Returns a Buffer containing the complete PDF.
   */
  async exportPdf(
    results: AssessmentResults,
    auth: AuthConfig,
  ): Promise<Buffer> {
    // Mask credentials before rendering
    const maskedExchanges = CredentialMasker.maskAll(results.exchanges, auth);

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const doc = new (PDFDocument as any)({
      size: 'A4',
      margins: { top: 50, bottom: 50, left: 50, right: 50 },
      info: {
        Title: 'CSAPI Compliance Assessment Report',
        Author: 'CSAPI Compliance Assessor',
        Subject: `Compliance report for ${results.endpointUrl}`,
      },
      bufferPages: true,
    });

    // Collect PDF output into a buffer
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));

    const finished = new Promise<Buffer>((resolve, reject) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', (err: Error) => reject(err));
    });

    // ─── Page 1: Title & Summary ───────────────────────────────────

    // Title
    doc
      .font('Helvetica-Bold')
      .fontSize(24)
      .text('CSAPI Compliance Assessment Report', { align: 'center' });

    doc.moveDown(1.5);

    // Endpoint and date info
    doc.font('Helvetica').fontSize(11);
    doc.text(`Endpoint: ${results.endpointUrl}`);
    doc.text(`Assessment ID: ${results.id}`);
    doc.text(`Started: ${results.startedAt}`);
    if (results.completedAt) {
      doc.text(`Completed: ${results.completedAt}`);
    }
    doc.text(`Status: ${results.status}`);
    doc.text(`Exported: ${new Date().toISOString()}`);

    doc.moveDown(1.5);

    // Overall compliance percentage (large)
    const pct = results.summary.compliancePercent;
    doc.font('Helvetica-Bold').fontSize(48).text(`${pct.toFixed(1)}%`, {
      align: 'center',
    });
    doc.font('Helvetica').fontSize(12).text('Overall Compliance', {
      align: 'center',
    });

    doc.moveDown(1);

    // Summary statistics table
    doc.font('Helvetica-Bold').fontSize(14).text('Summary');
    doc.moveDown(0.5);

    doc.font('Helvetica').fontSize(10);
    const summary = results.summary;

    const summaryLines = [
      `Total Tests: ${summary.totalTests}`,
      `Passed: ${summary.passed}    Failed: ${summary.failed}    Skipped: ${summary.skipped}`,
      `Total Classes: ${summary.totalClasses}`,
      `Classes Passed: ${summary.classesPassed}    Classes Failed: ${summary.classesFailed}    Classes Skipped: ${summary.classesSkipped}`,
      `Duration: ${(summary.durationMs / 1000).toFixed(1)}s`,
    ];

    for (const line of summaryLines) {
      doc.text(line);
    }

    doc.moveDown(1);

    // Disclaimer
    doc.font('Helvetica-Oblique').fontSize(8).text(DISCLAIMER, {
      align: 'left',
    });

    // ─── Page 2+: Per-Conformance-Class Sections ───────────────────

    for (const classResult of results.classes) {
      doc.addPage();
      this.renderClassSection(doc, classResult);
    }

    // ─── Finalize ──────────────────────────────────────────────────

    doc.end();

    return finished;
  }

  /**
   * Render a conformance class section on the current page.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  private renderClassSection(doc: any, classResult: ConformanceClassResult): void {
    // Class name and status badge
    const statusBadge =
      classResult.status === 'pass'
        ? '[PASS]'
        : classResult.status === 'fail'
          ? '[FAIL]'
          : '[SKIP]';

    doc
      .font('Helvetica-Bold')
      .fontSize(16)
      .text(`${classResult.className}  ${statusBadge}`);

    doc.font('Helvetica').fontSize(9).text(classResult.classUri);
    doc.moveDown(0.5);

    // Test counts
    doc.font('Helvetica').fontSize(10);
    doc.text(
      `Pass: ${classResult.counts.pass}    ` +
        `Fail: ${classResult.counts.fail}    ` +
        `Skip: ${classResult.counts.skip}    ` +
        `Total: ${classResult.tests.length}`,
    );

    doc.moveDown(1);

    // Failed tests detail
    const failedTests = classResult.tests.filter((t) => t.status === 'fail');
    if (failedTests.length > 0) {
      doc.font('Helvetica-Bold').fontSize(12).text('Failed Tests');
      doc.moveDown(0.5);

      for (const test of failedTests) {
        doc.font('Helvetica-Bold').fontSize(10).text(test.testName);
        doc.font('Courier').fontSize(8).text(test.requirementUri);
        if (test.failureMessage) {
          doc
            .font('Helvetica')
            .fontSize(9)
            .text(`Reason: ${test.failureMessage}`);
        }
        doc.moveDown(0.5);
      }
    }

    // Skipped tests (brief)
    const skippedTests = classResult.tests.filter((t) => t.status === 'skip');
    if (skippedTests.length > 0) {
      doc.font('Helvetica-Bold').fontSize(12).text('Skipped Tests');
      doc.moveDown(0.3);

      for (const test of skippedTests) {
        doc.font('Helvetica').fontSize(9).text(`- ${test.testName}`);
        if (test.skipReason) {
          doc.font('Helvetica').fontSize(8).text(`  Reason: ${test.skipReason}`);
        }
      }
      doc.moveDown(0.5);
    }
  }
}
